// Code generated by protoc-gen-go. DO NOT EDIT.
// source: homehub.proto

package homehub

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Result int32

const (
	Result_RECEIVED_NEW       Result = 0
	Result_RECEIVED_UPDATED   Result = 1
	Result_RECEIVED_UNCHANGED Result = 2
	Result_DECLINED           Result = 10
)

var Result_name = map[int32]string{
	0:  "RECEIVED_NEW",
	1:  "RECEIVED_UPDATED",
	2:  "RECEIVED_UNCHANGED",
	10: "DECLINED",
}
var Result_value = map[string]int32{
	"RECEIVED_NEW":       0,
	"RECEIVED_UPDATED":   1,
	"RECEIVED_UNCHANGED": 2,
	"DECLINED":           10,
}

func (x Result) String() string {
	return proto.EnumName(Result_name, int32(x))
}
func (Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_homehub_84edbe8a45f17ccd, []int{0}
}

type CheckInRequest struct {
	// agentId is expected to be a self-generated stable 64-character long hashed machine id
	AgentId string `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// web service http access port
	WebPort int32 `protobuf:"varint,3,opt,name=webPort,proto3" json:"webPort,omitempty"`
	// port for video stream live feed
	StreamPort int32 `protobuf:"varint,4,opt,name=streamPort,proto3" json:"streamPort,omitempty"`
	// port for meta information (ambient temperature, humidity, cpu etc.)
	MetaPort             int32    `protobuf:"varint,5,opt,name=metaPort,proto3" json:"metaPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckInRequest) Reset()         { *m = CheckInRequest{} }
func (m *CheckInRequest) String() string { return proto.CompactTextString(m) }
func (*CheckInRequest) ProtoMessage()    {}
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_homehub_84edbe8a45f17ccd, []int{0}
}
func (m *CheckInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckInRequest.Unmarshal(m, b)
}
func (m *CheckInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckInRequest.Marshal(b, m, deterministic)
}
func (dst *CheckInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckInRequest.Merge(dst, src)
}
func (m *CheckInRequest) XXX_Size() int {
	return xxx_messageInfo_CheckInRequest.Size(m)
}
func (m *CheckInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckInRequest proto.InternalMessageInfo

func (m *CheckInRequest) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *CheckInRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CheckInRequest) GetWebPort() int32 {
	if m != nil {
		return m.WebPort
	}
	return 0
}

func (m *CheckInRequest) GetStreamPort() int32 {
	if m != nil {
		return m.StreamPort
	}
	return 0
}

func (m *CheckInRequest) GetMetaPort() int32 {
	if m != nil {
		return m.MetaPort
	}
	return 0
}

type Ack struct {
	Result               Result   `protobuf:"varint,1,opt,name=result,proto3,enum=Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ack) Reset()         { *m = Ack{} }
func (m *Ack) String() string { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()    {}
func (*Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_homehub_84edbe8a45f17ccd, []int{1}
}
func (m *Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ack.Unmarshal(m, b)
}
func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ack.Marshal(b, m, deterministic)
}
func (dst *Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ack.Merge(dst, src)
}
func (m *Ack) XXX_Size() int {
	return xxx_messageInfo_Ack.Size(m)
}
func (m *Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_Ack.DiscardUnknown(m)
}

var xxx_messageInfo_Ack proto.InternalMessageInfo

func (m *Ack) GetResult() Result {
	if m != nil {
		return m.Result
	}
	return Result_RECEIVED_NEW
}

func init() {
	proto.RegisterType((*CheckInRequest)(nil), "CheckInRequest")
	proto.RegisterType((*Ack)(nil), "Ack")
	proto.RegisterEnum("Result", Result_name, Result_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HomeHubClient is the client API for HomeHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HomeHubClient interface {
	// Every hub is expected to check in repeatedly. Data can be sent only to a successfully
	// checked-in hub.
	CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*Ack, error)
}

type homeHubClient struct {
	cc *grpc.ClientConn
}

func NewHomeHubClient(cc *grpc.ClientConn) HomeHubClient {
	return &homeHubClient{cc}
}

func (c *homeHubClient) CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/HomeHub/CheckIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HomeHubServer is the server API for HomeHub service.
type HomeHubServer interface {
	// Every hub is expected to check in repeatedly. Data can be sent only to a successfully
	// checked-in hub.
	CheckIn(context.Context, *CheckInRequest) (*Ack, error)
}

func RegisterHomeHubServer(s *grpc.Server, srv HomeHubServer) {
	s.RegisterService(&_HomeHub_serviceDesc, srv)
}

func _HomeHub_CheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeHubServer).CheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HomeHub/CheckIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeHubServer).CheckIn(ctx, req.(*CheckInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HomeHub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HomeHub",
	HandlerType: (*HomeHubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckIn",
			Handler:    _HomeHub_CheckIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "homehub.proto",
}

func init() { proto.RegisterFile("homehub.proto", fileDescriptor_homehub_84edbe8a45f17ccd) }

var fileDescriptor_homehub_84edbe8a45f17ccd = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0x87, 0xed, 0xfe, 0x75, 0xbe, 0xcc, 0x19, 0x82, 0x48, 0xd9, 0x61, 0x8e, 0x1d, 0x64, 0x28,
	0xe4, 0x30, 0x3f, 0x41, 0x6d, 0x82, 0x2b, 0x48, 0x19, 0x41, 0xe7, 0x51, 0xda, 0xee, 0xc5, 0x4a,
	0xed, 0x32, 0x93, 0x54, 0xbf, 0x8b, 0x9f, 0x56, 0xcc, 0xd6, 0xa9, 0xc7, 0xe7, 0x79, 0x2e, 0x3f,
	0x7e, 0x70, 0x52, 0xa8, 0x0a, 0x8b, 0x3a, 0x63, 0x5b, 0xad, 0xac, 0x9a, 0x7e, 0x79, 0x30, 0x8c,
	0x0a, 0xcc, 0xcb, 0x78, 0x23, 0xf1, 0xbd, 0x46, 0x63, 0x69, 0x00, 0x7e, 0xfa, 0x82, 0x1b, 0x1b,
	0xaf, 0x03, 0x6f, 0xe2, 0xcd, 0x8e, 0x65, 0x83, 0xae, 0xac, 0xd7, 0x1a, 0x8d, 0x09, 0x5a, 0xfb,
	0xb2, 0xc3, 0x9f, 0xf2, 0x89, 0xd9, 0x52, 0x69, 0x1b, 0xb4, 0x27, 0xde, 0xac, 0x2b, 0x1b, 0xa4,
	0x63, 0x00, 0x63, 0x35, 0xa6, 0x95, 0x8b, 0x1d, 0x17, 0xff, 0x18, 0x3a, 0x82, 0x7e, 0x85, 0x36,
	0x75, 0xb5, 0xeb, 0xea, 0x81, 0xa7, 0x97, 0xd0, 0x0e, 0xf3, 0x92, 0x5e, 0x40, 0x4f, 0xa3, 0xa9,
	0xdf, 0xac, 0xdb, 0x33, 0x9c, 0xfb, 0x4c, 0x3a, 0x94, 0x7b, 0x7d, 0xb5, 0x82, 0xde, 0xce, 0x50,
	0x02, 0x03, 0x29, 0x22, 0x11, 0xaf, 0x04, 0x7f, 0x4e, 0xc4, 0x13, 0x39, 0xa2, 0x67, 0x40, 0x0e,
	0xe6, 0x71, 0xc9, 0xc3, 0x07, 0xc1, 0x89, 0x47, 0xcf, 0x81, 0xfe, 0xda, 0x24, 0x5a, 0x84, 0xc9,
	0x9d, 0xe0, 0xa4, 0x45, 0x07, 0xd0, 0xe7, 0x22, 0xba, 0x8f, 0x13, 0xc1, 0x09, 0xcc, 0xaf, 0xc1,
	0x5f, 0xa8, 0x0a, 0x17, 0x75, 0x46, 0x27, 0xe0, 0xef, 0x6f, 0xa2, 0xa7, 0xec, 0xff, 0x61, 0xa3,
	0x0e, 0x0b, 0xf3, 0xf2, 0x76, 0x0c, 0xa3, 0x57, 0xc5, 0xb6, 0x59, 0xad, 0xd3, 0x52, 0x7d, 0xb0,
	0xe6, 0x66, 0x93, 0x17, 0x58, 0xa5, 0x4b, 0x2f, 0xeb, 0xb9, 0xc3, 0x6f, 0xbe, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x49, 0x03, 0x21, 0x3b, 0x81, 0x01, 0x00, 0x00,
}
